/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmEmpleado.java
 *
 * Created on 24/11/2016, 12:06:49 AM
 */
package VISTA;

import MODELO.Empleado;
import DATOS.datosEmpleado;
import ComponenteOtros.*;
//import REPORTES.ReporteEmpleado;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author cesaralx!!
 */
public class frmEmpleado extends javax.swing.JFrame {
//    private ReporteEmpleado jasper;
    private frmUsuario usr;
    /** Creates new form FrmEmpleado */
    public frmEmpleado() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
//        jasper = new ReporteEmpleado();
    }
    Metodos m = new Metodos() {};
    String ImagenURL;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    public void Mostrar(JPanel p) {
        try {
            //se asigna a "url" el archivo de imagen seleccionado
            URL url = m.getObtener();
            //se lo coloca en memoria
            m.cargar_imagen(url);
            //se aÃ±ade al contenedor
            p.add(new mipanel(m.Obtener_imagen_de_Buffer(), p.getSize()) {});
            p.setVisible(true);
            p.repaint();
        } catch (Exception ex) {
            Logger.getLogger(Metodos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /*
     * Metodo para Buscar:
     */
     public void buscarEmpleado()
     {
         Empleado emp = null;
        try {
            emp = datosEmpleado.buscarEmpleadoDNI(Integer.parseInt(jtfDniE.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
        }
        if (emp != null) {
            try {
                jtfNroEmpleado.setText(String.valueOf(emp.getNroEmpleado()));
                jtfDniE.setText(String.valueOf(emp.getDni()));
                jtfNombreE.setText(emp.getNombre());
                jtfApellidoE.setText(emp.getApellido());
                jtfEdadE.setText(String.valueOf(emp.getEdad()));
                jtfTelefonoE.setText(emp.getTelefono());
                jcboSexoE.setSelectedItem(emp.getSexo());
                jtfCelularE.setText(emp.getCelular());
                jtfEmailE.setText(emp.getEmail());
                jtfDireccionE.setText(emp.getDireccion());
                jtfUsuario.setText(emp.getUser());
                URL url = new URL(emp.getImagen());
                m.setObtener(url);
                m.Mostrar(jpnImagen);
            } catch (MalformedURLException ex) {
                Logger.getLogger(frmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No exite");
        }
     }
    public void LimpiarTextos()
    {
        jtfNroEmpleado.setText("");
        jtfDniE.setText("");
        jtfNombreE.setText("");
        jtfApellidoE.setText("");
        jtfEdadE.setText("");
        jtfEmailE.setText("");
        jtfTelefonoE.setText("");
        jtfCelularE.setText("");
        jtfDireccionE.setText("");
        jtfUsuario.setText("");
        jpnImagen.removeAll();
    }

    public void EstadoButton(boolean b)
    {
        jbnNuevoE.setEnabled(!b);
        jbnAgregarE.setEnabled(b);
        jbnAbrirE.setEnabled(b);
        jbnCancelarE.setEnabled(b);
        jbnBuscarE.setEnabled(!b);
        jbnEditarE.setEnabled(!b);
        jbnEliminarE.setEnabled(!b);
        jbnMostrarE.setEnabled(!b);

    }
    public void activarTextos(boolean t)
    {
        jtfNombreE.setEditable(t);
        jtfApellidoE.setEditable(t);
        jtfEdadE.setEditable(t);
        jcboSexoE.setEnabled(t);
        jtfEmailE.setEditable(t);
        jtfTelefonoE.setEditable(t);
        jtfCelularE.setEditable(t);
        jtfDireccionE.setEditable(t);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNroEmpleado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jpnImagen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfDniE = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfNombreE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfApellidoE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfDireccionE = new javax.swing.JTextField();
        jtfEdadE = new javax.swing.JTextField();
        jtfEmailE = new javax.swing.JTextField();
        jtfTelefonoE = new javax.swing.JFormattedTextField();
        jtfCelularE = new javax.swing.JFormattedTextField();
        jcboSexoE = new javax.swing.JComboBox();
        jbnBuscarE = new javax.swing.JButton();
        jbnSalirE = new javax.swing.JButton();
        jbnEditarE = new javax.swing.JButton();
        jbnEliminarE = new javax.swing.JButton();
        jbnNuevoE = new javax.swing.JButton();
        jbnAbrirE = new javax.swing.JButton();
        jbnMostrarE = new javax.swing.JButton();
        jbnAgregarE = new javax.swing.JButton();
        jbnCancelarE = new javax.swing.JButton();
        jlbUsuario = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(81, 105, 138));

        jPanel1.setBackground(new java.awt.Color(247, 254, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nro Empleado:");

        jtfNroEmpleado.setEditable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jpnImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpnImagenLayout = new javax.swing.GroupLayout(jpnImagen);
        jpnImagen.setLayout(jpnImagenLayout);
        jpnImagenLayout.setHorizontalGroup(
            jpnImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        jpnImagenLayout.setVerticalGroup(
            jpnImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Dni:");

        try {
            jtfDniE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDniE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDniEActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jtfNombreE.setEditable(false);
        jtfNombreE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreEKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Apellido:");

        jtfApellidoE.setEditable(false);
        jtfApellidoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfApellidoEKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Edad:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Sexo:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Telefono:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Celular:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Direccion:");

        jtfDireccionE.setEditable(false);

        jtfEdadE.setEditable(false);

        jtfEmailE.setEditable(false);
        jtfEmailE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailEActionPerformed(evt);
            }
        });

        jtfTelefonoE.setEditable(false);
        try {
            jtfTelefonoE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)-###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jtfCelularE.setEditable(false);
        try {
            jtfCelularE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jcboSexoE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "F", "M" }));
        jcboSexoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboSexoEActionPerformed(evt);
            }
        });

        jbnBuscarE.setText("...");
        jbnBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnBuscarEActionPerformed(evt);
            }
        });

        jbnSalirE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbnSalirE.setText("Salir");
        jbnSalirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnSalirEActionPerformed(evt);
            }
        });

        jbnEditarE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbnEditarE.setText("Editar");
        jbnEditarE.setEnabled(false);
        jbnEditarE.setPreferredSize(new java.awt.Dimension(75, 23));
        jbnEditarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnEditarEActionPerformed(evt);
            }
        });

        jbnEliminarE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbnEliminarE.setText("Eliminar");
        jbnEliminarE.setEnabled(false);
        jbnEliminarE.setMaximumSize(new java.awt.Dimension(75, 23));
        jbnEliminarE.setMinimumSize(new java.awt.Dimension(75, 23));
        jbnEliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnEliminarEActionPerformed(evt);
            }
        });

        jbnNuevoE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbnNuevoE.setText("Nuevo");
        jbnNuevoE.setPreferredSize(new java.awt.Dimension(65, 23));
        jbnNuevoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnNuevoEActionPerformed(evt);
            }
        });

        jbnAbrirE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbnAbrirE.setText("Examinar");
        jbnAbrirE.setEnabled(false);
        jbnAbrirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAbrirEActionPerformed(evt);
            }
        });

        jbnMostrarE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbnMostrarE.setText("Mostrar");
        jbnMostrarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnMostrarEActionPerformed(evt);
            }
        });

        jbnAgregarE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbnAgregarE.setText("Agregrar");
        jbnAgregarE.setEnabled(false);
        jbnAgregarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAgregarEActionPerformed(evt);
            }
        });

        jbnCancelarE.setText("Cancelar");
        jbnCancelarE.setEnabled(false);
        jbnCancelarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnCancelarEActionPerformed(evt);
            }
        });

        jlbUsuario.setText("Uusario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbnSalirE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jcboSexoE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtfEdadE, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel9))
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfTelefonoE)
                                            .addComponent(jtfCelularE, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jtfEmailE, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jtfDireccionE, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfApellidoE, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtfDniE, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbnBuscarE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlbUsuario)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfUsuario))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbnAbrirE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbnNuevoE, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbnAgregarE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbnEditarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbnEliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbnMostrarE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbnCancelarE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfNroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDniE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jbnBuscarE)
                            .addComponent(jlbUsuario)
                            .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfApellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfEdadE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jcboSexoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jtfCelularE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfTelefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtfEmailE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jtfDireccionE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbnCancelarE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbnMostrarE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbnEliminarE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbnNuevoE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbnAbrirE, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jbnAgregarE, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jbnEditarE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbnSalirE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("REGISTRO DE EMPLEADO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnAbrirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAbrirEActionPerformed
        // TODO add your handling code here:
        jpnImagen.removeAll();
        m.Abrir_Dialogo(jpnImagen);
        ImagenURL = m.ObtenerUrl();
    }//GEN-LAST:event_jbnAbrirEActionPerformed

    private void jtfDniEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDniEActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtfDniEActionPerformed

    private void jtfNombreEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreEKeyTyped
        // TODO add your handling code here:
        if (!String.valueOf(evt.getKeyChar()).matches("[a-zA-Z]|\\s")) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfNombreEKeyTyped

    private void jtfApellidoEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApellidoEKeyTyped
        // TODO add your handling code here:
        if (!String.valueOf(evt.getKeyChar()).matches("[a-zA-Z]|\\s")) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfApellidoEKeyTyped

    private void jtfEmailEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailEActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jtfEmailEActionPerformed

    private void jbnAgregarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAgregarEActionPerformed
        // TODO add your handling code here:
        frmUsuario usr = new frmUsuario();
   if(jtfDniE.getText().compareTo("")!=0 && jtfNombreE.getText().compareTo("")!=0&& jtfApellidoE.getText().compareTo("")!=0 
      && jtfEdadE.getText().compareTo("")!=0 && (jtfCelularE.getText().compareTo("")!=0 || jtfTelefonoE.getText().compareTo("")!=0)
      && jtfDireccionE.getText().compareTo("")!=0){
        Empleado em = new Empleado() {};
        em.setDni(Integer.parseInt(jtfDniE.getText()));
        em.setNombre(jtfNombreE.getText());
        em.setApellido(jtfApellidoE.getText());
        em.setEdad(Integer.parseInt(jtfEdadE.getText()));
        em.setTelefono((jtfTelefonoE.getText()));
        em.setSexo((String) jcboSexoE.getSelectedItem());
        em.setCelular(jtfCelularE.getText());
        em.setEmail(jtfEmailE.getText());
        em.setDireccion(jtfDireccionE.getText());
        em.setImagen(ImagenURL);
        try {
            datosEmpleado.insertarEmpleado(em, usr);
           
            LimpiarTextos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error BD: " + e.getMessage());
        }
        JOptionPane.showMessageDialog(null, "[ Datos Agregados ]","Correcto",JOptionPane.INFORMATION_MESSAGE);
   }else{
       JOptionPane.showMessageDialog(null, "Llene los Campos Obligatorios","Error: Datos no Validos",JOptionPane.ERROR_MESSAGE);
       getToolkit().beep();        //Emite un sonido de alerta
   }

    }//GEN-LAST:event_jbnAgregarEActionPerformed

    private void jbnBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnBuscarEActionPerformed
        // TODO add your handling code here:
        if (jtfDniE.getText().compareTo("")!= 0) {
            int result = JOptionPane.showConfirmDialog(
                    this, "Deseas Buscar al Empleado para Modificarlo?",
                    "Mensaje..!!",
                    JOptionPane.YES_NO_OPTION);

            if (result == JOptionPane.YES_OPTION) {
                buscarEmpleado();
                jbnNuevoE.setEnabled(false);
                jbnMostrarE.setEnabled(false);
                jbnCancelarE.setEnabled(true);
                jbnAbrirE.setEnabled(true);
                jbnEditarE.setEnabled(true);
                activarTextos(true);
            }
            if (result == JOptionPane.NO_OPTION) {
                buscarEmpleado();
                jbnEliminarE.setEnabled(true);
                jbnNuevoE.setEnabled(false);
                jbnCancelarE.setEnabled(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese DNI que Desea Buscar");
        }
    }//GEN-LAST:event_jbnBuscarEActionPerformed

    private void jbnEliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnEliminarEActionPerformed
        // TODO add your handling code here:
        try {
            Empleado emp = datosEmpleado.buscarEmpleadoDNI(Integer.parseInt(jtfDniE.getText()));
            if (emp == null) {
                JOptionPane.showMessageDialog(null, "No existe");
            } else {
                datosEmpleado.eliminarEmpleadoDNI(emp.getDni());
                JOptionPane.showMessageDialog(null, "Se Elimino Exitosamente..OKz!!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
        }
        LimpiarTextos();
    }//GEN-LAST:event_jbnEliminarEActionPerformed

    private void jbnMostrarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnMostrarEActionPerformed
        // TODO add your handling code here:
        JDListaEmpleados LE = new JDListaEmpleados(this, true);
        LE.setVisible(true);
    }//GEN-LAST:event_jbnMostrarEActionPerformed

    private void jbnNuevoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnNuevoEActionPerformed
        // TODO add your handling code here:
        LimpiarTextos();
        EstadoButton(true);
        activarTextos(true);
    }//GEN-LAST:event_jbnNuevoEActionPerformed

    private void jbnEditarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnEditarEActionPerformed
        // TODO add your handling code here:
        Empleado emp;
            try {
                emp = datosEmpleado.buscarEmpleadoSinIM(Integer.parseInt(jtfNroEmpleado.getText()));
                emp.setDni(Integer.parseInt(jtfDniE.getText()));
                emp.setNombre(jtfNombreE.getText());
                emp.setApellido(jtfApellidoE.getText());
                emp.setEdad(Integer.parseInt(jtfEdadE.getText()));
                emp.setTelefono(jtfTelefonoE.getText());
                emp.setSexo((String) jcboSexoE.getSelectedItem());
                emp.setCelular(jtfCelularE.getText());
                emp.setEmail(jtfEmailE.getText());
                emp.setDireccion(jtfDireccionE.getText());
                emp.setImagen(ImagenURL);
                datosEmpleado.actualizarEmpleado(emp);
                JOptionPane.showMessageDialog(null, " [ Datos Actualizados ]");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error BD: " + e.getMessage());
            }
        LimpiarTextos();
    }//GEN-LAST:event_jbnEditarEActionPerformed

    private void jbnSalirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnSalirEActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbnSalirEActionPerformed

    private void jbnCancelarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnCancelarEActionPerformed
        // TODO add your handling code here:
        LimpiarTextos();
        activarTextos(false);
        jbnCancelarE.setEnabled(false);
        jbnEliminarE.setEnabled(false);
        jbnNuevoE.setEnabled(true);
        jbnMostrarE.setEnabled(true);
        jbnBuscarE.setEnabled(true);
        jbnAgregarE.setEnabled(false);
        jbnAbrirE.setEnabled(false);
        jbnEditarE.setEnabled(false);
    }//GEN-LAST:event_jbnCancelarEActionPerformed

    private void jcboSexoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboSexoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboSexoEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmEmpleado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbnAbrirE;
    private javax.swing.JButton jbnAgregarE;
    private javax.swing.JButton jbnBuscarE;
    private javax.swing.JButton jbnCancelarE;
    private javax.swing.JButton jbnEditarE;
    private javax.swing.JButton jbnEliminarE;
    private javax.swing.JButton jbnMostrarE;
    private javax.swing.JButton jbnNuevoE;
    private javax.swing.JButton jbnSalirE;
    private javax.swing.JComboBox jcboSexoE;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JPanel jpnImagen;
    private javax.swing.JTextField jtfApellidoE;
    private javax.swing.JFormattedTextField jtfCelularE;
    private javax.swing.JTextField jtfDireccionE;
    private javax.swing.JFormattedTextField jtfDniE;
    private javax.swing.JTextField jtfEdadE;
    private javax.swing.JTextField jtfEmailE;
    private javax.swing.JTextField jtfNombreE;
    private javax.swing.JTextField jtfNroEmpleado;
    private javax.swing.JFormattedTextField jtfTelefonoE;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
