/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import java.text.SimpleDateFormat;
import java.util.*;

/**
 *
 * @author cesaralx
 */
public class frmMainMenu extends javax.swing.JFrame {

     private frmUsuario login;
     public String userLogeado;
     
    public frmMainMenu(frmUsuario x) {
        initComponents();
        login = x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbMenu = new javax.swing.JToolBar();
        jbnAnadir = new javax.swing.JButton();
        jbnEliminar = new javax.swing.JButton();
        jbnBuscar = new javax.swing.JButton();
        jbnNuevo = new javax.swing.JButton();
        jpnMain = new javax.swing.JPanel();
        jlbFecha = new javax.swing.JLabel();
        jlbCodeFecha = new javax.swing.JLabel();
        jlbHora = new javax.swing.JLabel();
        jlbCodeHora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbMenuImagen = new javax.swing.JLabel();
        jlbUsuarios = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jmbMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiSesion = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiVenta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiCategoria = new javax.swing.JMenuItem();
        jmiCliente = new javax.swing.JMenuItem();
        jmiEmpleado = new javax.swing.JMenuItem();
        jmiProducto = new javax.swing.JMenuItem();
        jmiProveedor = new javax.swing.JMenuItem();
        jmiDetProv = new javax.swing.JMenuItem();
        jmiUsuario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiReporteEm = new javax.swing.JMenuItem();
        jmiReporteProd = new javax.swing.JMenuItem();
        jmiReporteCat = new javax.swing.JMenuItem();
        jmiReporteCliente = new javax.swing.JMenuItem();
        jmiReporteUsr = new javax.swing.JMenuItem();
        jmiReporteProv = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setType(java.awt.Window.Type.UTILITY);

        jtbMenu.setBackground(new java.awt.Color(255, 255, 255));
        jtbMenu.setRollover(true);

        jbnAnadir.setBackground(new java.awt.Color(255, 255, 255));
        jbnAnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/new.png"))); // NOI18N
        jbnAnadir.setText("Anadir");
        jbnAnadir.setFocusable(false);
        jbnAnadir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnAnadir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbMenu.add(jbnAnadir);

        jbnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jbnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/remove_from_database.png"))); // NOI18N
        jbnEliminar.setText("Eliminar");
        jbnEliminar.setFocusable(false);
        jbnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbMenu.add(jbnEliminar);

        jbnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jbnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/search_database.png"))); // NOI18N
        jbnBuscar.setText("Buscar");
        jbnBuscar.setFocusable(false);
        jbnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbMenu.add(jbnBuscar);

        jbnNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jbnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/add_to_database.png"))); // NOI18N
        jbnNuevo.setText("Nuevo");
        jbnNuevo.setFocusable(false);
        jbnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbMenu.add(jbnNuevo);

        jpnMain.setBackground(new java.awt.Color(70, 99, 138));
        jpnMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbFecha.setForeground(new java.awt.Color(255, 255, 255));
        jlbFecha.setText("Fecha");

        jlbCodeFecha.setForeground(new java.awt.Color(255, 255, 255));
        jlbCodeFecha.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));

        jlbHora.setForeground(new java.awt.Color(255, 255, 255));
        jlbHora.setText("Hora");

        jlbCodeHora.setForeground(new java.awt.Color(255, 255, 255));
        jlbCodeHora.setText(new SimpleDateFormat("hh:mm:ss a").format(new Date()));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO AL SISTEMA");

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DE MINISUPER ++");

        jlbMenuImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/p031_1_00.jpg"))); // NOI18N

        jlbUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jlbUsuarios.setText("Usuario:");

        javax.swing.GroupLayout jpnMainLayout = new javax.swing.GroupLayout(jpnMain);
        jpnMain.setLayout(jpnMainLayout);
        jpnMainLayout.setHorizontalGroup(
            jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnMainLayout.createSequentialGroup()
                        .addComponent(jlbUsuarios)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnMainLayout.createSequentialGroup()
                        .addGroup(jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnMainLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(93, 93, 93))
                            .addGroup(jpnMainLayout.createSequentialGroup()
                                .addGroup(jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jpnMainLayout.createSequentialGroup()
                                        .addComponent(jlbFecha)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlbCodeFecha)
                                        .addGap(155, 155, 155)
                                        .addComponent(jlbHora)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlbCodeHora)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)))
                        .addComponent(jlbMenuImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jpnMainLayout.setVerticalGroup(
            jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMainLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnMainLayout.createSequentialGroup()
                        .addGroup(jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbFecha)
                            .addComponent(jlbCodeFecha)
                            .addComponent(jlbHora)
                            .addComponent(jlbCodeHora))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(jlbMenuImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbUsuarios)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jMenu1.setText("Inicio");

        jmiSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/24x24/delete_user.png"))); // NOI18N
        jmiSesion.setText("Cerrar Sesion");
        jmiSesion.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jmiSesionMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jmiSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSesionActionPerformed(evt);
            }
        });
        jMenu1.add(jmiSesion);

        jmiSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/24x24/delete_home.png"))); // NOI18N
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmiSalir);

        jmbMenu.add(jMenu1);

        jMenu2.setText("Venta");

        jmiVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/24x24/add_to_shopping_cart.png"))); // NOI18N
        jmiVenta.setText("Generar Venta");
        jmiVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVentaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiVenta);

        jmbMenu.add(jMenu2);

        jMenu3.setText("Mantenimiento");

        jmiCategoria.setText("Categoria");
        jmiCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCategoriaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiCategoria);

        jmiCliente.setText("Cliente");
        jmiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteActionPerformed(evt);
            }
        });
        jMenu3.add(jmiCliente);

        jmiEmpleado.setText("Empleado");
        jmiEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEmpleadoActionPerformed(evt);
            }
        });
        jMenu3.add(jmiEmpleado);

        jmiProducto.setText("Producto");
        jmiProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductoActionPerformed(evt);
            }
        });
        jMenu3.add(jmiProducto);

        jmiProveedor.setText("Proveedor");
        jmiProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProveedorActionPerformed(evt);
            }
        });
        jMenu3.add(jmiProveedor);

        jmiDetProv.setText("Detalle-Proveedor");
        jMenu3.add(jmiDetProv);

        jmiUsuario.setText("Usuario");
        jmiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(jmiUsuario);

        jmbMenu.add(jMenu3);

        jMenu4.setText("Reportes");

        jmiReporteEm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/24x24/phone_book_edit.png"))); // NOI18N
        jmiReporteEm.setText("Reporte Empleados");
        jmiReporteEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReporteEmActionPerformed(evt);
            }
        });
        jMenu4.add(jmiReporteEm);

        jmiReporteProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/24x24/phone_book_edit.png"))); // NOI18N
        jmiReporteProd.setText("Reporte Producto");
        jmiReporteProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReporteProdActionPerformed(evt);
            }
        });
        jMenu4.add(jmiReporteProd);

        jmiReporteCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/24x24/phone_book_edit.png"))); // NOI18N
        jmiReporteCat.setText("Reporte Categoria");
        jmiReporteCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReporteCatActionPerformed(evt);
            }
        });
        jMenu4.add(jmiReporteCat);

        jmiReporteCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/24x24/phone_book_edit.png"))); // NOI18N
        jmiReporteCliente.setText("Reporte Cliente");
        jmiReporteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReporteClienteActionPerformed(evt);
            }
        });
        jMenu4.add(jmiReporteCliente);

        jmiReporteUsr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/24x24/phone_book_edit.png"))); // NOI18N
        jmiReporteUsr.setText("Reporte Usuarios");
        jmiReporteUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReporteUsrActionPerformed(evt);
            }
        });
        jMenu4.add(jmiReporteUsr);

        jmiReporteProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/24x24/phone_book_edit.png"))); // NOI18N
        jmiReporteProv.setText("Reporte Proveedor");
        jmiReporteProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiReporteProvActionPerformed(evt);
            }
        });
        jMenu4.add(jmiReporteProv);

        jmbMenu.add(jMenu4);

        jMenu5.setText("Ayuda");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/24x24/support.png"))); // NOI18N
        jMenuItem1.setText("Acerca de");
        jMenu5.add(jMenuItem1);

        jmbMenu.add(jMenu5);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiEmpleadoActionPerformed

    private void jmiSesionMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jmiSesionMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiSesionMenuKeyPressed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSesionActionPerformed
         login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jmiSesionActionPerformed

    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
         frmRegCliente Frmcl= new frmRegCliente();
         this.disable();
        Frmcl.setVisible(true);
    }//GEN-LAST:event_jmiClienteActionPerformed

    private void jmiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuarioActionPerformed
         frmRegUsuario FrmUs= new frmRegUsuario();
         this.dispose();
        FrmUs.setVisible(true);
    }//GEN-LAST:event_jmiUsuarioActionPerformed

    private void jmiVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVentaActionPerformed
         frmNuevaCompra FrmComp= new frmNuevaCompra();
           this.dispose();
        FrmComp.setVisible(true);
    }//GEN-LAST:event_jmiVentaActionPerformed

    private void jmiProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductoActionPerformed
     
          frmProducto Frmp= new frmProducto();
            this.dispose();
        Frmp.setVisible(true);
      
    }//GEN-LAST:event_jmiProductoActionPerformed

    private void jmiReporteProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReporteProdActionPerformed
        // TODO add your handling code here:
        JDListaProductos litProd = new JDListaProductos(this, rootPaneCheckingEnabled);
//        this.dispose();
        litProd.setVisible(true);
    }//GEN-LAST:event_jmiReporteProdActionPerformed

    private void jmiReporteCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReporteCatActionPerformed
        JDListaCategorias litCat = new JDListaCategorias(this, rootPaneCheckingEnabled) ;
      
//        this.dispose();
        litCat.setVisible(true);
    }//GEN-LAST:event_jmiReporteCatActionPerformed

    private void jmiCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCategoriaActionPerformed
        // TODO add your handling code here:
         frmCategoria frmC= new frmCategoria();
            this.dispose();
        frmC.setVisible(true);
    }//GEN-LAST:event_jmiCategoriaActionPerformed

    private void jmiReporteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReporteClienteActionPerformed
         JDListaClientes litCli = new JDListaClientes(this, rootPaneCheckingEnabled) ;
      
//        this.dispose();
        litCli.setVisible(true);
    }//GEN-LAST:event_jmiReporteClienteActionPerformed

    private void jmiReporteEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReporteEmActionPerformed
      JDListaEmpleados litEm = new JDListaEmpleados(this, rootPaneCheckingEnabled) ;
      
//        this.dispose();
        litEm.setVisible(true);
    }//GEN-LAST:event_jmiReporteEmActionPerformed

    private void jmiReporteUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReporteUsrActionPerformed
      JDListaUsuarios listUsr = new JDListaUsuarios(this, rootPaneCheckingEnabled) ;
//        this.dispose();
        listUsr.setVisible(true);
    }//GEN-LAST:event_jmiReporteUsrActionPerformed

    private void jmiReporteProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiReporteProvActionPerformed
  JDListaProveedores listProv = new JDListaProveedores(this, rootPaneCheckingEnabled) ;
        listProv.setVisible(true);
    }//GEN-LAST:event_jmiReporteProvActionPerformed

    private void jmiProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProveedorActionPerformed
        frmProveedor provedor = new frmProveedor() ;
        this.dispose();
        provedor.setVisible(true);
    }//GEN-LAST:event_jmiProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//              new frmMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbnAnadir;
    private javax.swing.JButton jbnBuscar;
    private javax.swing.JButton jbnEliminar;
    private javax.swing.JButton jbnNuevo;
    private javax.swing.JLabel jlbCodeFecha;
    private javax.swing.JLabel jlbCodeHora;
    private javax.swing.JLabel jlbFecha;
    private javax.swing.JLabel jlbHora;
    private javax.swing.JLabel jlbMenuImagen;
    public javax.swing.JLabel jlbUsuarios;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JMenuItem jmiCategoria;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiDetProv;
    private javax.swing.JMenuItem jmiEmpleado;
    private javax.swing.JMenuItem jmiProducto;
    private javax.swing.JMenuItem jmiProveedor;
    private javax.swing.JMenuItem jmiReporteCat;
    private javax.swing.JMenuItem jmiReporteCliente;
    private javax.swing.JMenuItem jmiReporteEm;
    private javax.swing.JMenuItem jmiReporteProd;
    private javax.swing.JMenuItem jmiReporteProv;
    private javax.swing.JMenuItem jmiReporteUsr;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmiSesion;
    private javax.swing.JMenuItem jmiUsuario;
    private javax.swing.JMenuItem jmiVenta;
    private javax.swing.JPanel jpnMain;
    private javax.swing.JToolBar jtbMenu;
    // End of variables declaration//GEN-END:variables
}
